steps:
  # Step 1: Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/ankita-sem2-project/ankita-100941771/app:$COMMIT_SHA'
      - '.'

  # Step 2: Push Docker Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'us-central1-docker.pkg.dev/ankita-sem2-project/ankita-100941771/app:$COMMIT_SHA'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

# This tells Cloud Build where to find the image
images:
  - 'us-central1-docker.pkg.dev/ankita-sem2-project/ankita-100941771/app:$COMMIT_SHA'

