steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/719998335017/ankita-100941771/$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/719998335017/ankita-100941771/$COMMIT_SHA']
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
triggers:
- name: dc-ankita-100941771
  github:
    push:
      branch: main # Or your branch name
  filename: cloudbuild.yaml
  approval:
    requiredApprovers:
      - 'ankitaktl5@gmail.com'
